"""Antwoorden oppikken uit GitHub-issues.

Twee stappen, met opzet:
1. We lezen jouw reactie en koppelen terug hoe we die begrepen hebben.
2. Pas na jouw bevestiging wordt het een 'bevestigde' beslissing in de
   kennisbasis en gaan de wachtende taken weer lopen.

Is het antwoord ambigu, dan stellen we één gerichte vervolgvraag in plaats van
te kiezen. Alleen reacties van de repo-eigenaar tellen als antwoord.
"""

from __future__ import annotations

import json
import re

from .db import ProjectScope
from .models import TaskStatus, now
from .notify.github import GitHubClient
from .projects import Project

_CONFIRM = re.compile(r"^\s*(ja|klopt|akkoord|correct|prima|yes|ok|oké|okay)\b", re.I)
_DENY = re.compile(r"^\s*(nee|niet|onjuist|fout|no)\b", re.I)


def _state(row) -> dict:
    try:
        return json.loads(row["answer"] or "{}")
    except (ValueError, TypeError):
        return {}


def process_answers(
    *, scope: ProjectScope, project: Project, client: GitHubClient
) -> list[str]:
    """Verwerkt nieuwe reacties. Geeft een lijst met wat er gebeurd is."""
    if not project.github_repo:
        return []
    actions: list[str] = []

    for row in scope.pending_questions():
        number = row["issue_number"]
        if not number:
            continue
        state = _state(row)
        seen = int(state.get("seen_comment_id") or 0)
        comments = [c for c in client.owner_comments(project.github_repo, number)
                    if int(c["id"]) > seen]
        if not comments:
            continue
        latest = comments[-1]
        body = (latest.get("body") or "").strip()
        state["seen_comment_id"] = int(latest["id"])

        if row["status"] == "awaiting_confirmation":
            if _CONFIRM.match(body):
                item_id = project.knowledge.append_decision(
                    title=row["text"][:80],
                    body=state.get("interpretation", "") or state.get("raw", ""),
                    source=f"antwoord op issue #{number}",
                    confirmed_by_human=True,
                )
                scope.set_question(
                    row["id"], status="answered",
                    answer=json.dumps({**state, "decision": item_id}),
                    answered_at=now(),
                )
                requeued = _requeue(scope, row["id"])
                client.comment(
                    project.github_repo, number,
                    f"Vastgelegd als **{item_id}** in de kennisbasis."
                    + (f" {requeued} taak(en) hervat." if requeued else "")
                    + "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
                )
                client.close_issue(project.github_repo, number)
                actions.append(f"{row['id']}: bevestigd als {item_id}")
                continue
            if _DENY.match(body) or len(body) > 3:
                # Correctie: opnieuw terugkoppelen in plaats van kiezen.
                state["interpretation"] = body
                state["raw"] = body
                scope.set_question(row["id"], answer=json.dumps(state))
                client.comment(
                    project.github_repo, number,
                    f"Aangepast. Ik lees je antwoord nu als:\n\n> {body}\n\n"
                    "Klopt dat? Antwoord met **ja** om het vast te leggen."
                    "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
                )
                actions.append(f"{row['id']}: correctie ontvangen, opnieuw ter bevestiging")
                continue

        # Eerste reactie: terugkoppelen hoe we het gelezen hebben.
        state["interpretation"] = body
        state["raw"] = body
        scope.set_question(
            row["id"], status="awaiting_confirmation", answer=json.dumps(state)
        )
        client.comment(
            project.github_repo, number,
            f"Ik heb je antwoord gelezen als:\n\n> {body}\n\n"
            "Klopt dat? Antwoord met **ja** om het als beslissing vast te leggen, "
            "of corrigeer het in één zin."
            "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
        )
        actions.append(f"{row['id']}: antwoord ontvangen, ter bevestiging voorgelegd")

    return actions


def _requeue(scope: ProjectScope, question_id: int) -> int:
    tasks = scope.tasks_waiting_on(question_id)
    for task in tasks:
        if TaskStatus(task["status"]).waits_for_human:
            scope.set_task(task["id"], status=TaskStatus.QUEUED.value,
                           blocked_by_question=None)
    return len(tasks)


def answer_locally(
    *, scope: ProjectScope, project: Project, question_id: int, answer: str
) -> str:
    """Een geparkeerde vraag beantwoorden vanaf de opdrachtregel.

    Zelfde regel: dit is een menselijk antwoord, dus het levert een bevestigde
    beslissing op.
    """
    row = scope.question(question_id)
    if row is None:
        raise ValueError(f"vraag {question_id} bestaat niet in {scope.slug}")
    item_id = project.knowledge.append_decision(
        title=row["text"][:80],
        body=answer,
        source=f"antwoord op vraag #{question_id} via de opdrachtregel",
        confirmed_by_human=True,
    )
    scope.set_question(
        question_id, status="answered",
        answer=json.dumps({"interpretation": answer, "decision": item_id}),
        answered_at=now(),
    )
    _requeue(scope, question_id)
    return item_id
