"""Antwoorden oppikken uit GitHub-issues.

Twee stappen, met opzet:
1. We lezen jouw reactie en koppelen terug hoe we die begrepen hebben.
2. Pas na jouw bevestiging wordt het een 'bevestigde' beslissing in de
   kennisbasis en gaan de wachtende taken weer lopen.

Is het antwoord ambigu, dan stellen we één gerichte vervolgvraag in plaats van
te kiezen. Alleen reacties van de repo-eigenaar tellen als antwoord.
"""

from __future__ import annotations

import json
import re

from .answer_session import Act, AnswerFlow
from .db import ProjectScope
from .models import TaskStatus, now
from .notify.github import GitHubClient
from .projects import Project

VERVALLABEL = "orch:vervallen"

_CONFIRM = re.compile(r"^\s*(ja|klopt|akkoord|correct|prima|yes|ok|oké|okay)\b", re.I)
_DENY = re.compile(r"^\s*(nee|niet|onjuist|fout|no)\b", re.I)


def _state(row) -> dict:
    try:
        return json.loads(row["answer"] or "{}")
    except (ValueError, TypeError):
        return {}


def verval_gemarkeerde_vragen(*, scope, project, client) -> list[str]:
    """Laat vragen vervallen die met `orch:vervallen` zijn gemarkeerd.

    Sommige vragen zijn niet te beantwoorden. Dat overkwam vraag #7 van
    padelmq-ai-product-engine: de poort tegen verzonnen waarden bood als enige
    optie de broncode-regel waar die verzonnen waarde in stond, dus was het
    enige beantwoordbare antwoord een bevestiging van precies wat die poort
    moest tegenhouden.

    Zo'n vraag mag niet beantwoord worden om er vanaf te zijn. Ze vervalt: er
    wordt GEEN beslissing vastgelegd, GEEN kennisitem aangemaakt en GEEN
    antwoord in de audittrail gezet. Er komt alleen te staan dat de vraag is
    vervallen en waarom. De taak gaat terug in de wachtrij en stelt de vraag
    zo nodig opnieuw -- dan met de opties die hij inmiddels wel heeft.
    """
    if not project.github_repo:
        return []
    try:
        gemarkeerd = {int(i["number"])
                      for i in client.issues_with_label(project.github_repo, VERVALLABEL)}
    except Exception:  # noqa: BLE001 - een label ophalen mag de lus niet slopen
        return []
    if not gemarkeerd:
        return []

    acties: list[str] = []
    for row in scope.pending_questions():
        nummer = row["issue_number"]
        if not nummer or int(nummer) not in gemarkeerd:
            continue
        scope.set_question(int(row["id"]), status="vervallen", answered_at=now())
        scope.log("vraag-vervallen",
                  {"question_id": int(row["id"]), "issue": int(nummer),
                   "reden": "met orch:vervallen gemarkeerd; niet beantwoordbaar",
                   "vraag": row["text"][:200]},
                  task_id=row["task_id"])
        # De rem op herhaalde betaalde opdrachten moet mee weg. Blijft hij
        # staan, dan gaat de taak wel terug in de wachtrij maar blokkeert de
        # rem hem meteen opnieuw: prompt en branch zijn immers onveranderd. Dat
        # gebeurde bij vraag #7, binnen veertig seconden, twee keer.
        hervat = _requeue(scope, int(row["id"]), vergeet_handtekeningen=True)
        client.comment(
            project.github_repo, int(nummer),
            "Deze vraag is vervallen verklaard. Er is **geen** antwoord vastgelegd,"
            " geen beslissing en geen kennisitem: de vraag was niet te beantwoorden"
            " zonder iets te bevestigen dat niet klopt.\n\n"
            f"{hervat} taak/taken staan weer in de wachtrij. Komt dezelfde vraag"
            " opnieuw, dan is het met de opties die er nu wel zijn."
            "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
        )
        client.close_issue(project.github_repo, int(nummer))
        acties.append(f"vraag {row['id']}: vervallen, {hervat} taak/taken hervat")
    return acties


def process_answers(
    *, scope: ProjectScope, project: Project, client: GitHubClient
) -> list[str]:
    """Haalt menselijke antwoorden uit GitHub-issues en voert ze door de poort.

    De koppeling loopt via de database, niet via de tekst van een issue: we
    beginnen bij de openstaande vragen van DIT project en zoeken daar het
    issuenummer bij. Een antwoord kan daardoor niet bij een ander project of een
    andere taak belanden, ook niet als twee projecten dezelfde repository delen.

    De beoordeling van het antwoord gebeurt in AnswerFlow, dezelfde poort die de
    opdrachtregel en spraak gebruiken. Dus ook hier: hoogstens één
    verduidelijking, en daarna blijft de blokkade staan in plaats van dat er iets
    ingevuld wordt.
    """
    if not project.github_repo:
        return []
    actions: list[str] = []

    for row in scope.pending_questions():
        number = row["issue_number"]
        if not number:
            continue

        state = _state(row)
        seen = int(state.get("seen_comment_id") or 0)
        # De orkestrator schrijft met de token van de eigenaar. Zijn eigen
        # terugkoppeling komt dus terug als "reactie van de eigenaar", en werd
        # als antwoord op zijn eigen vraag gelezen: "Ik leg dit vast als: Ik leg
        # dit vast als: ...", en daarna een afbreking die niemand had gegeven.
        # We onthouden daarom wat we zelf geplaatst hebben en slaan dat over.
        eigen = {int(i) for i in (state.get("eigen_reacties") or [])}
        comments = [c for c in client.owner_comments(project.github_repo, number)
                    if int(c["id"]) > seen and int(c["id"]) not in eigen]
        if not comments:
            continue

        flow = AnswerFlow(scope, channel="github")
        session_id = flow.open(int(row["id"]), row["text"], row["task_id"])

        stap = None
        for comment in comments:
            tekst = (comment.get("body") or "").strip()
            state["seen_comment_id"] = int(comment["id"])
            if not tekst:
                continue
            stap = flow.submit(session_id, tekst)
            if stap.act is Act.APPLY:
                break

        if stap is None:
            scope.set_question(row["id"], answer=json.dumps(state))
            continue

        geplaatst: list[int] = []
        actions.extend(
            _voer_stap_uit(
                scope=scope, project=project, client=client, row=row,
                number=int(number), stap=stap, geplaatst=geplaatst,
            )
        )
        # APPLY schrijft de vraag zelf weg (met de beslissing erin); die staat
        # mag deze boekhouding niet overschrijven.
        vers = scope.question(row["id"])
        if vers is not None and (vers["status"] or "") == "answered":
            continue
        state["eigen_reacties"] = sorted(eigen | set(geplaatst))
        scope.set_question(row["id"], answer=json.dumps(state))
    return actions


def _plaats(client, geplaatst, repo: str, number: int, body: str) -> None:
    """Plaatst een reactie en noteert het id, zodat we hem later niet als
    antwoord van de eigenaar terugkrijgen."""
    cid = client.comment(repo, number, body)
    if geplaatst is not None and cid:
        geplaatst.append(int(cid))


def _voer_stap_uit(*, scope, project, client, row, number: int, stap,
                   geplaatst: list[int] | None = None) -> list[str]:
    """Vertaalt wat de poort besliste naar een reactie in het issue."""
    voet = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"

    if stap.act is Act.APPLY:
        item_id = record_human_decision(
            scope=scope, project=project, question_id=int(row["id"]),
            answer=stap.text,
            source=f"antwoord op issue #{number}",
        )
        hervat = scope.tasks(status="queued")
        _plaats(client, geplaatst,
            project.github_repo, number,
            f"Vastgelegd als **{item_id}** in de kennisbasis van `{project.slug}`.\n\n"
            f"> {stap.text}\n\n"
            + (f"Taak #{row['task_id']} staat weer in de wachtrij en wordt automatisch "
               "hervat." if row["task_id"] else "")
            + f"\n\nOpenstaand in dit project: {len(hervat)} taak(en)." + voet,
        )
        client.close_issue(project.github_repo, number)
        return [f"vraag {row['id']}: vastgelegd als {item_id}, taak hervat"]

    if stap.act is Act.ASK_CONFIRMATION:
        _plaats(client, geplaatst, project.github_repo, number, stap.text + voet)
        return [f"vraag {row['id']}: ter bevestiging voorgelegd"]

    if stap.act is Act.ASK_CLARIFICATION:
        _plaats(client, geplaatst,
            project.github_repo, number,
            stap.text + "\n\n_Dit is de enige verduidelijking die ik vraag. Kom ik er "
            "daarna niet uit, dan blijft de taak geblokkeerd in plaats van dat ik "
            "iets invul._" + voet,
        )
        return [f"vraag {row['id']}: één verduidelijking gevraagd"]

    # KEEP_BLOCKED
    _plaats(client, geplaatst, project.github_repo, number,
            stap.text + f"\n\n_Reden: {stap.reason}_" + voet)
    return [f"vraag {row['id']}: blijft geblokkeerd ({stap.reason})"]


def _requeue(scope: ProjectScope, question_id: int, *,
             vergeet_handtekeningen: bool = False) -> int:
    tasks = scope.tasks_waiting_on(question_id)
    for task in tasks:
        if TaskStatus(task["status"]).waits_for_human:
            scope.set_task(task["id"], status=TaskStatus.QUEUED.value,
                           blocked_by_question=None)
            if vergeet_handtekeningen:
                scope.forget_signatures(int(task["id"]))
    return len(tasks)


def record_human_decision(
    *, scope: ProjectScope, project: Project, question_id: int, answer: str, source: str
) -> str:
    """Legt een menselijk antwoord vast als bevestigde beslissing en hervat het werk.

    Dit is het enige punt waar status 'bevestigd' ontstaat. Elk kanaal — GitHub,
    opdrachtregel, spraak — komt hier uit, zodat de regel op één plek staat.
    """
    row = scope.question(question_id)
    if row is None:
        raise ValueError(f"vraag {question_id} bestaat niet in {scope.slug}")
    item_id = project.knowledge.append_decision(
        title=row["text"][:80],
        body=answer,
        source=source,
        confirmed_by_human=True,
    )
    scope.set_question(
        question_id, status="answered",
        answer=json.dumps({"interpretation": answer, "decision": item_id}),
        answered_at=now(),
    )
    _requeue(scope, question_id)
    return item_id


def answer_locally(
    *, scope: ProjectScope, project: Project, question_id: int, answer: str
) -> str:
    """Een geparkeerde vraag beantwoorden vanaf de opdrachtregel.

    Zelfde regel: dit is een menselijk antwoord, dus het levert een bevestigde
    beslissing op.
    """
    return record_human_decision(
        scope=scope, project=project, question_id=question_id, answer=answer,
        source=f"antwoord op vraag #{question_id} via de opdrachtregel",
    )
