"""Antwoorden oppikken uit GitHub-issues.

Twee stappen, met opzet:
1. We lezen jouw reactie en koppelen terug hoe we die begrepen hebben.
2. Pas na jouw bevestiging wordt het een 'bevestigde' beslissing in de
   kennisbasis en gaan de wachtende taken weer lopen.

Is het antwoord ambigu, dan stellen we één gerichte vervolgvraag in plaats van
te kiezen. Alleen reacties van de repo-eigenaar tellen als antwoord.
"""

from __future__ import annotations

import json
import re

from .answer_session import Act, AnswerFlow
from .db import ProjectScope
from .models import TaskStatus, now
from .notify.github import GitHubClient
from .projects import Project

_CONFIRM = re.compile(r"^\s*(ja|klopt|akkoord|correct|prima|yes|ok|oké|okay)\b", re.I)
_DENY = re.compile(r"^\s*(nee|niet|onjuist|fout|no)\b", re.I)


def _state(row) -> dict:
    try:
        return json.loads(row["answer"] or "{}")
    except (ValueError, TypeError):
        return {}


def process_answers(
    *, scope: ProjectScope, project: Project, client: GitHubClient
) -> list[str]:
    """Haalt menselijke antwoorden uit GitHub-issues en voert ze door de poort.

    De koppeling loopt via de database, niet via de tekst van een issue: we
    beginnen bij de openstaande vragen van DIT project en zoeken daar het
    issuenummer bij. Een antwoord kan daardoor niet bij een ander project of een
    andere taak belanden, ook niet als twee projecten dezelfde repository delen.

    De beoordeling van het antwoord gebeurt in AnswerFlow, dezelfde poort die de
    opdrachtregel en spraak gebruiken. Dus ook hier: hoogstens één
    verduidelijking, en daarna blijft de blokkade staan in plaats van dat er iets
    ingevuld wordt.
    """
    if not project.github_repo:
        return []
    actions: list[str] = []

    for row in scope.pending_questions():
        number = row["issue_number"]
        if not number:
            continue

        state = _state(row)
        seen = int(state.get("seen_comment_id") or 0)
        comments = [c for c in client.owner_comments(project.github_repo, number)
                    if int(c["id"]) > seen]
        if not comments:
            continue

        flow = AnswerFlow(scope, channel="github")
        session_id = flow.open(int(row["id"]), row["text"], row["task_id"])

        stap = None
        for comment in comments:
            tekst = (comment.get("body") or "").strip()
            state["seen_comment_id"] = int(comment["id"])
            if not tekst:
                continue
            stap = flow.submit(session_id, tekst)
            if stap.act is Act.APPLY:
                break

        scope.set_question(row["id"], answer=json.dumps(state))
        if stap is None:
            continue

        actions.extend(
            _voer_stap_uit(
                scope=scope, project=project, client=client, row=row,
                number=int(number), stap=stap,
            )
        )
    return actions


def _voer_stap_uit(*, scope, project, client, row, number: int, stap) -> list[str]:
    """Vertaalt wat de poort besliste naar een reactie in het issue."""
    voet = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"

    if stap.act is Act.APPLY:
        item_id = record_human_decision(
            scope=scope, project=project, question_id=int(row["id"]),
            answer=stap.text,
            source=f"antwoord op issue #{number}",
        )
        hervat = scope.tasks(status="queued")
        client.comment(
            project.github_repo, number,
            f"Vastgelegd als **{item_id}** in de kennisbasis van `{project.slug}`.\n\n"
            f"> {stap.text}\n\n"
            + (f"Taak #{row['task_id']} staat weer in de wachtrij en wordt automatisch "
               "hervat." if row["task_id"] else "")
            + f"\n\nOpenstaand in dit project: {len(hervat)} taak(en)." + voet,
        )
        client.close_issue(project.github_repo, number)
        return [f"vraag {row['id']}: vastgelegd als {item_id}, taak hervat"]

    if stap.act is Act.ASK_CONFIRMATION:
        client.comment(project.github_repo, number, stap.text + voet)
        return [f"vraag {row['id']}: ter bevestiging voorgelegd"]

    if stap.act is Act.ASK_CLARIFICATION:
        client.comment(
            project.github_repo, number,
            stap.text + "\n\n_Dit is de enige verduidelijking die ik vraag. Kom ik er "
            "daarna niet uit, dan blijft de taak geblokkeerd in plaats van dat ik "
            "iets invul._" + voet,
        )
        return [f"vraag {row['id']}: één verduidelijking gevraagd"]

    # KEEP_BLOCKED
    client.comment(
        project.github_repo, number,
        stap.text + f"\n\n_Reden: {stap.reason}_" + voet,
    )
    return [f"vraag {row['id']}: blijft geblokkeerd ({stap.reason})"]


def _requeue(scope: ProjectScope, question_id: int) -> int:
    tasks = scope.tasks_waiting_on(question_id)
    for task in tasks:
        if TaskStatus(task["status"]).waits_for_human:
            scope.set_task(task["id"], status=TaskStatus.QUEUED.value,
                           blocked_by_question=None)
    return len(tasks)


def record_human_decision(
    *, scope: ProjectScope, project: Project, question_id: int, answer: str, source: str
) -> str:
    """Legt een menselijk antwoord vast als bevestigde beslissing en hervat het werk.

    Dit is het enige punt waar status 'bevestigd' ontstaat. Elk kanaal — GitHub,
    opdrachtregel, spraak — komt hier uit, zodat de regel op één plek staat.
    """
    row = scope.question(question_id)
    if row is None:
        raise ValueError(f"vraag {question_id} bestaat niet in {scope.slug}")
    item_id = project.knowledge.append_decision(
        title=row["text"][:80],
        body=answer,
        source=source,
        confirmed_by_human=True,
    )
    scope.set_question(
        question_id, status="answered",
        answer=json.dumps({"interpretation": answer, "decision": item_id}),
        answered_at=now(),
    )
    _requeue(scope, question_id)
    return item_id


def answer_locally(
    *, scope: ProjectScope, project: Project, question_id: int, answer: str
) -> str:
    """Een geparkeerde vraag beantwoorden vanaf de opdrachtregel.

    Zelfde regel: dit is een menselijk antwoord, dus het levert een bevestigde
    beslissing op.
    """
    return record_human_decision(
        scope=scope, project=project, question_id=question_id, answer=answer,
        source=f"antwoord op vraag #{question_id} via de opdrachtregel",
    )
