"""Een vastgelopen taak weer op gang brengen, via een label in GitHub.

Waarom dit bestaat. De rem op herhaalde betaalde opdrachten houdt een taak
tegen zodra dezelfde opdracht bij dezelfde toestand van de branch al eens naar
de uitvoerder is gestuurd. Dat is goed: nog eens betalen levert hetzelfde
antwoord op. Maar de rem meldt zich zonder vraag, en een melding zonder vraag
is niet te beantwoorden. De taak staat dan `blocked` en er is geen enkele knop
om hem weer te laten lopen -- ook niet nadat de reden van de blokkade is
weggenomen. Dat overkwam taak 3 van padelmq-ai-product-engine.

De knop is een label op het opdrachtissue: `orch:hervat`. Het is met opzet
hetzelfde soort handeling als `orch:vervallen`, want dat is de enige bediening
die er is zonder opdrachtregel of serverzitting.

Wat er gebeurt is bewust beperkt. De taak gaat terug in de wachtrij en de rem
voor die ene taak wordt gewist, zodat dezelfde opdracht opnieuw verstuurd mag
worden. Er wordt niets beantwoord, niets besloten en niets aan de kennisbasis
toegevoegd. En het wissen van de rem wordt met zoveel woorden gemeld, want het
betekent dat er opnieuw betaald kan worden voor werk dat er misschien al staat.
"""

from __future__ import annotations

from .db import ProjectScope
from .models import TaskStatus
from .notify.github import GitHubClient
from .projects import Project

HERVATLABEL = "orch:hervat"

_ONDERTEKENING = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def hervat_gemarkeerde_taken(
    *, scope: ProjectScope, project: Project, client: GitHubClient
) -> list[str]:
    """Zet taken waarvan het opdrachtissue `orch:hervat` draagt weer in de wachtrij."""
    if not project.github_repo:
        return []
    try:
        gemarkeerd = client.issues_with_label(project.github_repo, HERVATLABEL)
    except Exception:  # noqa: BLE001 - een label ophalen mag de lus niet slopen
        return []

    acties: list[str] = []
    for issue in gemarkeerd:
        nummer = int(issue["number"])
        # Alleen de eigenaar mag werk hervatten. Dezelfde poort als bij het
        # aannemen van een opdracht; anders zou een willekeurige lezer betaalde
        # aanroepen kunnen uitlokken.
        if not client.issue_author_is_owner(project.github_repo, issue):
            acties.append(f"issue #{nummer}: hervatting genegeerd, niet van de eigenaar")
            continue

        task_id = scope.task_for_issue(nummer)
        if task_id is None:
            client.comment(
                project.github_repo, nummer,
                "Ik kan dit label niet uitvoeren: bij dit issue hoort geen aangenomen"
                " taak. Zet `orch:hervat` op het opdrachtissue zelf -- dat is het issue"
                " met `orch:accepted` waarop staat als welke taak het is aangenomen."
                + _ONDERTEKENING,
            )
            client.remove_label(project.github_repo, nummer, HERVATLABEL)
            acties.append(f"issue #{nummer}: hervatting geweigerd, geen taak gevonden")
            continue

        taak = scope.task(task_id)
        if taak is None:
            client.remove_label(project.github_repo, nummer, HERVATLABEL)
            acties.append(f"issue #{nummer}: hervatting geweigerd, taak {task_id} bestaat niet")
            continue

        huidige = TaskStatus(taak["status"])
        if huidige is TaskStatus.DONE:
            client.comment(
                project.github_repo, nummer,
                f"Taak **#{task_id}** is al afgerond. Ik hervat niets; er zou dan"
                " opnieuw betaald werk gedaan worden aan iets dat af is."
                + _ONDERTEKENING,
            )
            client.remove_label(project.github_repo, nummer, HERVATLABEL)
            acties.append(f"taak {task_id}: al klaar, niet hervat")
            continue

        gewist = scope.forget_signatures(task_id)
        scope.set_task(task_id, status=TaskStatus.QUEUED.value, blocked_by_question=None)
        scope.log(
            "taak-hervat",
            {"issue": nummer, "vorige_status": huidige.value,
             "handtekeningen_gewist": gewist,
             "reden": f"met {HERVATLABEL} gemarkeerd door de eigenaar"},
            task_id=task_id,
        )
        client.comment(
            project.github_repo, nummer,
            f"Taak **#{task_id}** staat weer in de wachtrij (was `{huidige.value}`).\n\n"
            f"De rem op herhaalde betaalde opdrachten is voor deze taak gewist"
            f" ({gewist} vastgelegde toestand(en)). Dezelfde opdracht mag dus opnieuw"
            " naar de uitvoerder, en dat kost opnieuw geld. Bestaand werk in de"
            " werkmap blijft staan en wordt hergebruikt zolang de verificatie"
            " groen is.\n\n"
            "Er is **geen** antwoord vastgelegd, geen beslissing en geen kennisitem."
            + _ONDERTEKENING,
        )
        client.remove_label(project.github_repo, nummer, HERVATLABEL)
        acties.append(
            f"taak {task_id}: hervat vanaf {huidige.value}, {gewist} handtekening(en) gewist"
        )
    return acties
