"""Werk aannemen via GitHub.

Zonder dit moet elke taak met de hand op de opdrachtregel worden ingevoerd, en
dan blijft er een mens tussen de opdracht en het werk staan -- precies wat deze
orkestrator moet wegnemen.

Een issue met het label 'orch:task' wordt een taak. De acceptatiecriteria komen
uit de checklist in de issuetekst; zonder criteria wordt de taak niet
aangenomen, want dan valt niet vast te stellen wanneer ze klaar is.
"""

from __future__ import annotations

import re

TAAKLABEL = "orch:task"
AANGENOMENLABEL = "orch:accepted"

# - [ ] criterium   of   - [x] criterium
_CHECKLIST = re.compile(r"^\s*[-*]\s*\[[ xX]\]\s*(?P<tekst>.+?)\s*$", re.M)
# Alles onder een kop die met "acceptatie" begint telt ook als criterium.
_KOP = re.compile(r"^#{1,6}\s*acceptatie", re.I | re.M)


def acceptatiecriteria(body: str) -> list[str]:
    """Haalt de criteria uit de issuetekst.

    Eerst een checklist, want die is ondubbelzinnig. Staat die er niet, dan de
    regels onder een kop die met 'acceptatie' begint. Wordt er niets gevonden,
    dan is de lijst leeg en wordt de taak geweigerd -- er wordt niets verzonnen.
    """
    body = body or ""
    treffers = [m.group("tekst").strip() for m in _CHECKLIST.finditer(body)]
    if treffers:
        return [t for t in treffers if t]

    kop = _KOP.search(body)
    if not kop:
        return []
    rest = body[kop.end():]
    criteria = []
    for regel in rest.splitlines():
        schoon = regel.strip()
        if not schoon:
            continue
        if schoon.startswith("#"):
            break
        criteria.append(re.sub(r"^[-*]\s*", "", schoon))
    return [c for c in criteria if c]


def spec_uit_body(body: str) -> str:
    """De opdrachttekst zonder de acceptatiechecklist."""
    zonder = _CHECKLIST.sub("", body or "")
    kop = _KOP.search(zonder)
    if kop:
        zonder = zonder[: kop.start()]
    return zonder.strip()


def intake(*, scope, project, client) -> list[str]:
    """Neemt nieuwe opdrachten aan. Geeft terug wat er gebeurd is."""
    if not project.github_repo:
        return []

    acties: list[str] = []
    for issue in client.issues_with_label(project.github_repo, TAAKLABEL):
        nummer = int(issue["number"])
        labels = {l["name"] for l in issue.get("labels", [])}
        if AANGENOMENLABEL in labels:
            continue  # al aangenomen; idempotent bij een herstart

        if not client.issue_author_is_owner(project.github_repo, issue):
            acties.append(f"issue #{nummer}: genegeerd, niet van de eigenaar")
            continue

        body = issue.get("body") or ""
        criteria = acceptatiecriteria(body)
        if not criteria:
            client.comment(
                project.github_repo, nummer,
                "Ik neem deze opdracht niet aan: er staan geen acceptatiecriteria in.\n\n"
                "Zonder criteria kan ik niet vaststellen wanneer het werk klaar is, en dan "
                "zou ik dat zelf moeten invullen. Zet ze als checklist in de beschrijving:\n\n"
                "```\n- [ ] wat er moet gelden als het af is\n- [ ] npm run test geeft exit 0\n```"
                "\n\nZodra ze erin staan pak ik het vanzelf op."
                "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
            )
            acties.append(f"issue #{nummer}: geweigerd, geen acceptatiecriteria")
            continue

        task_id = scope.add_task(
            title=issue.get("title") or f"issue #{nummer}",
            spec=spec_uit_body(body) or (issue.get("title") or ""),
            acceptance=criteria,
        )
        scope.log("opdracht-aangenomen",
                  {"issue": nummer, "criteria": len(criteria)}, task_id=task_id)
        client.add_labels(project.github_repo, nummer, [AANGENOMENLABEL])
        client.comment(
            project.github_repo, nummer,
            f"Aangenomen als taak **#{task_id}** in `{project.slug}`, met "
            f"{len(criteria)} acceptatiecriteri{'um' if len(criteria) == 1 else 'a'}.\n\n"
            "Ik meld me hier weer met een pull request, of met een vraag als er een "
            "beslissing nodig is die ik niet mag nemen."
            "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
        )
        acties.append(f"issue #{nummer}: aangenomen als taak {task_id}")
    return acties
